version: '3'
services:
  dvmsbotcard:
    image: dvmsbotcard:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dvmsbotcard
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
